version: '2'

services:

  mongo:

    image: mongo

    restart: always

   

  node-tools:

    build:

      context: ./

    depends_on:

      - mongo

    command: bash

    working_dir: /app

    volumes:

      - .:/app/